### ISSUE TITLE
move to libmir

### ISSUE THREAD

**Issue by yannick** [tamediadigital/je#18]
@maveonair  would it be possible to attach BSL licence and move this over to libmir too? i guess no one at tamedia uses this anyway.

/cc @9il

**Comment by cohadar** [comment]
I have no objections. This is not used by TDA or anyone that I know of in Tamedia.
It is a simple tool and contains no Tamedia proprietary information.

I would flatten the commit history as a security precaution before moving it away from tamedia, but that is it.

**Comment by maveonair** [comment]
@yannick @9il Could you please flatten the commit history to the recent commit and then we will transfer the repository to your preferred destination.

**Comment by 9il** [comment]
Hey all. Thanks for transfer. I don't have the permission to push:
`remote: Permission to tamediadigital/je.git denied to 9il.`

**Comment by maveonair** [comment]
@9il I added you as a collaborator. You probably must accept the invite before you can push again.

**Comment by 9il** [comment]
done

**Comment by maveonair** [comment]
@9il I made you to an admin. Can you please try to move this repository to your prefered Github account / origanization?

**Comment by 9il** [comment]
```
Transfer ownership
Organization members cannot transfer repositories
```

It can be moved to @libmir

**Comment by maveonair** [comment]
> You don’t have the permission to create public repositories on libmir

**Comment by 9il** [comment]
Do you need permission? I thought you can just transfer the repo

**Comment by 9il** [comment]
Ah, yes, you need permission. I have sent an invitation.

**Comment by yannick** [comment]
thank you guys
